language: c++
compiler:
 - gcc

os:
#  - linux
  - osx

branches:
  only:
    - master
    - feature/travisci

before_install:
  - travis-ci/deps-${TRAVIS_OS_NAME}.sh

install: true

before_script:
  - travis-ci/cmake-${TRAVIS_OS_NAME}.sh

script:
  - cd build
  - make
